# -*- coding: utf-8 -*-

"""
    swaggerpetstore

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
"""

from swaggerpetstore.decorators import lazy_property
from swaggerpetstore.configuration import Configuration
from swaggerpetstore.controllers.pet_controller import PetController
from swaggerpetstore.controllers.store_controller import StoreController
from swaggerpetstore.controllers.user_controller import UserController


class SwaggerpetstoreClient(object):

    config = Configuration

    @lazy_property
    def pet(self):
        return PetController()

    @lazy_property
    def store(self):
        return StoreController()

    @lazy_property
    def user(self):
        return UserController()


    def __init__(self,
                 o_auth_client_id=None,
                 o_auth_redirect_uri=None):
        if o_auth_client_id != None:
            Configuration.o_auth_client_id = o_auth_client_id
        if o_auth_redirect_uri != None:
            Configuration.o_auth_redirect_uri = o_auth_redirect_uri


